export const TOGGEL_THEME = "TOGGEL_THEME"

export const GET_BESTSELLER = "GET_BESTSELLER"
export const ADD_BESTSELLER = "ADD_BESTSELLER"
export const DELETE_BESTSELLER = "DELETE_BESTSELLER"
export const UPDATE_BESTSELLER = "UPDATE_BESTSELLER"

export const GET_CONTACT = "GET_CONTACT"
export const ADD_CONTACT = "ADD_CONTACT"
export const DELETE_CONTACT = "DELETE_CONTACT"
export const UPDATE_CONTACT = "UPDATE_CONTACT"